### ISSUE TITLE
Problem at startup accessory

### ISSUE THREAD

**Issue by maury77** [YinHangCode/homebridge-mi-gateway-fm#4]
Radio] Initializing MiGatewayFM accessory...
/usr/local/lib/node_modules/homebridge-mi-gateway-fm/index.js:49
    this.device = new miio.Device({
                  ^

TypeError: miio.Device is not a constructor
    at new MiGatewayFM (/usr/local/lib/node_modules/homebridge-mi-gateway-fm/index.js:49:19)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:275:29)

**Comment by antonybrro** [comment]
use older version of miio

`sudo npm install -g --unsafe-perm miio@0.14.1`
